dist: bionic

language: php

cache:
  directories:
    - vendor

git:
  submodules: false

php:
  - 7.3

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
  - composer self-update
  - composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}

install:
  - cp .env.travis .env
  - chmod 660 storage/
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

before_script:
  - php artisan migrate --no-interaction

script:
  - vendor/bin/phpunit --coverage-text

branches:
  only:
    - master
    - develop

notifications:
  email: false
