dist: bionic

language: php

cache:
  directories:
    - vendor

git:
  submodules: false

php:
  - 7.3

services:
  - mysql

before_install:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
  - composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}

install:
  - travis_retry composer install --prefer-source --no-interaction --no-suggest

before_script:
  - php artisan key:generate
  - php artisan migrate --no-interaction
  - php artisan passport:keys

script:
  - vendor/bin/phpunit --coverage-text

branches:
  only:
    - master
    - develop

notifications:
  email: false
