dist: bionic

language: php

cache:
  directories:
    - vendor

git:
  submodules: false

php:
  - 7.3

services:
  - mysql

before_install:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
  - composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
  - touch storage/oauth-private.key && touch storage/oauth-public.key

install:
  - travis_retry composer install --no-interaction --no-suggest --no-scripts

before_script:
  - php artisan key:generate
  - php artisan passport:keys --force
  - php artisan package:discover --ansi
  - php artisan migrate --no-interaction

script:
  - vendor/bin/phpunit --coverage-text

branches:
  only:
    - master
    - develop

notifications:
  email: false
